apiVersion: v1
kind: Service
metadata:
  name: load-blancer
spec:
  ports:
  # Порт сетевого балансировщика, на котором будут обслуживаться пользовательские запросы.
  - port: 80
    name: k8s-e876583acc6ec3a953ccd4ec6eac40b38d46d756
    # Порт контейнера, на котором доступно приложение.
    targetPort: 8080
  # Метки селектора, использованные в шаблоне подов при создании объекта Deployment.
  selector:
    app: gateway
  type: LoadBalancer
