name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build, publish to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Push to docker hub
        timeout-minutes: 15
        run: |
            docker build --no-cache -t andreevaa/gateway ./src/gateway/ && docker push andreevaa/gateway:latest
            docker build --no-cache -t andreevaa/rating ./src/rating/ && docker push andreevaa/rating:latest
            docker build --no-cache -t andreevaa/library ./src/library/ && docker push andreevaa/library:latest
            docker build --no-cache -t andreevaa/reservation ./src/reservation/ && docker push andreevaa/reservation:latest

      - name: Prepare Kube config
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
          KUBECONFIG_CA_FILE: '${{ secrets.KUBECONFIG_CA }}'
        run: |
          echo "$KUBECONFIG_FILE" > ./kube.config 
          echo "$KUBECONFIG_CA_FILE" > ./ca.pem 

      - name: 'Deploy DB'
        run: |
          cd k8s/postgres-chart
          helm upgrade db . --kubeconfig test.kubeconfig
          sleep 60

      - name: 'Deploy App'
        run: |
          cd k8s/services-chart
          help uninstall app
          helm upgrade app . --kubeconfig test.kubeconfig
          sleep 60

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        run: newman run v4/postman/collection.json --environment v4/postman/environment.json --insecure

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"          